# Generated by Django 4.2.26 on 2026-02-03 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AINote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('generated_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher')], default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_notes.standard')),
            ],
            options={
                'unique_together': {('name', 'standard')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order_index', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_notes.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentNote',
        ),
        migrations.AddField(
            model_name='masternote',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_notes.standard'),
        ),
        migrations.AddField(
            model_name='masternote',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_notes.subject'),
        ),
        migrations.AddField(
            model_name='masternote',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_notes.topic'),
        ),
        migrations.AddField(
            model_name='ainote',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_notes.standard'),
        ),
        migrations.AddField(
            model_name='ainote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ainote',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_notes.subject'),
        ),
        migrations.AddField(
            model_name='ainote',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_notes.topic'),
        ),
    ]
