# Generated by Django 4.2.26 on 2026-02-10 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_notes', '0003_seed_academic_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('mastered', 'Mastered'), ('revision_required', 'Revision Required')], default='locked', max_length=30)),
                ('mastery_score', models.FloatField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('revision_due', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_notes.topic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
