# Generated by Django 4.2.26 on 2026-02-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='strategy_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topics',
            field=models.JSONField(default=list),
        ),
    ]
