# Generated by Django 4.2.26 on 2025-11-12 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('grade_level', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/')),
                ('type', models.CharField(choices=[('system', 'System'), ('ai', 'AI'), ('student', 'Student')], default='system', max_length=16)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('source_link', models.URLField(blank=True, null=True)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
