# Generated by Django 4.2.26 on 2026-02-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='topic',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
